### ISSUE TITLE
> Voy a dejar esto por aquí para probar cómo va el pull request.

### ISSUE THREAD

**Issue by SalamandraDevs** [SalamandraDevs/salamandradevs#2]
> Voy a dejar esto por aquí para probar cómo va el pull request.

¿Cuál es el propósito de este patch?

_Originally posted by @SalamandraDevs in https://github.com/SalamandraDevs/salamandradevs/issues/1#issuecomment-1396282484_

**Comment by OdairTrujillo** [comment]
No pues que es bueno probar

**Comment by SalamandraDevs** [comment]
Ah ok, cerraré el asunto.
